[theme]
# Primary accent color for interactive elements
primaryColor = "#1E40AF"

# Background color for the main content area
backgroundColor = "#FFFFFF"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#F3F4F6"

# Color used for almost all text
textColor = "#1F2937"

# Font family for all text in the app
font = "sans serif"

[server]
# Max file size for uploads (in MB)
maxUploadSize = 10

# Max message size (in MB)
maxMessageSize = 10

[browser]
# Tab title
gatherUsageStats = false

# Show app in wide mode by default
[runner]
fastReruns = true
